// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/contacto" | "/precios" | "/sistema" | "/video/[slug]"
type AppRouteHandlerRoutes = "/api/admin-portafolio" | "/api/admin-portafolio-mdx" | "/api/admin/clear-cache" | "/api/auth/login" | "/api/bunny-status" | "/api/bunny-video-slug" | "/api/bunny-videos" | "/api/download" | "/api/newsletter" | "/api/orders" | "/api/page-config" | "/api/pages" | "/api/products" | "/api/thumbnail/[videoId]" | "/api/upload-image" | "/api/video-config" | "/api/webhooks/whatsapp"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = "/casos-de-exito" | "/organizaciones/[[...slug]]" | "/proyectos" | "/proyectos/[[...slug]]" | "/servicios/motion-desing" | "/videos/cabezamvilacmexp5rbeamconfiguracinlhvv12ugs9qn" | "/videos/contact-ce5-guia-de-contacto-extraterrestre-vela-minilibrito" | "/videos/crazypapa-studios-fanzine-glise-gray-alien-collection-chile-visualizacionrlh9h8" | "/videos/dgalobienvuwn5j" | "/videos/hight-lights-manojo-crazyroom-01fqvxpcixk3to" | "/videos/interview-master1uowugjpcphgr" | "/videos/lexlexreel-021au6f3dcllg7c" | "/videos/mastermasterzvpdgipktcoy" | "/videos/nueva-coleccion-kali-yuga" | "/videos/reel-version1wde9xzlvv49t"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/api/admin-portafolio": {}
  "/api/admin-portafolio-mdx": {}
  "/api/admin/clear-cache": {}
  "/api/auth/login": {}
  "/api/bunny-status": {}
  "/api/bunny-video-slug": {}
  "/api/bunny-videos": {}
  "/api/download": {}
  "/api/newsletter": {}
  "/api/orders": {}
  "/api/page-config": {}
  "/api/pages": {}
  "/api/products": {}
  "/api/thumbnail/[videoId]": { "videoId": string; }
  "/api/upload-image": {}
  "/api/video-config": {}
  "/api/webhooks/whatsapp": {}
  "/casos-de-exito": {}
  "/contacto": {}
  "/organizaciones/[[...slug]]": { "slug"?: string[]; }
  "/precios": {}
  "/proyectos": {}
  "/proyectos/[[...slug]]": { "slug"?: string[]; }
  "/servicios/motion-desing": {}
  "/sistema": {}
  "/video/[slug]": { "slug": string; }
  "/videos/cabezamvilacmexp5rbeamconfiguracinlhvv12ugs9qn": {}
  "/videos/contact-ce5-guia-de-contacto-extraterrestre-vela-minilibrito": {}
  "/videos/crazypapa-studios-fanzine-glise-gray-alien-collection-chile-visualizacionrlh9h8": {}
  "/videos/dgalobienvuwn5j": {}
  "/videos/hight-lights-manojo-crazyroom-01fqvxpcixk3to": {}
  "/videos/interview-master1uowugjpcphgr": {}
  "/videos/lexlexreel-021au6f3dcllg7c": {}
  "/videos/mastermasterzvpdgipktcoy": {}
  "/videos/nueva-coleccion-kali-yuga": {}
  "/videos/reel-version1wde9xzlvv49t": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
