import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
       <html lang="es">
      <body>
        <header>
          <Link href="/">Leandro Venegas</Link>
          <nav>
            <Link href="/proyectos">Proyectos</Link>
            <Link href="/organizaciones">Organizaciones</Link>
            <Link href="/contenidos">Contenidos</Link>
            <Link href="/contacto">Contacto</Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
